package-lock.json
package.json
src/components.d.ts
src/components/app-header/app-header.tsx
src/pages/open-forge-app/open-forge-app.tsx

also add a boolean to hide button on the app header when needed

feat(app header): add smooth scroll to the home page

---

src/pages/app-home/app-home.tsx

fix(home page): fixes smooth scrolling behavior

---

.firebaserc
.gitignore
.travis.yml
firebase.json
package.json
src/components/app-footer/app-footer.tsx
stencil.config.js

- Switch to Firebase dev for deployment
- Implement Travis for CI tests
- Test updating footer address (`PA` -> `Pennsylvania`)

Firebase dev

---

src/pages/app-contact/app-contact.tsx

fix(app-contact): style fix for contact page hero button color

---

src/pages/app-contact/app-contact.tsx

fix(app-contact): removed class nowrap from hero header

---

src/components.d.ts
sw.js

Hot-fix for unregistered service worker.

fix(sw.js): imports cdm 3.3.1 now

---

src/components.d.ts
src/components/app-img/app-img.tsx
src/components/app-nav-header/app-nav-header.tsx
src/components/content-graphic-lg/content-graphic-lg.tsx
src/pages/app-home/app-home.tsx
src/pages/open-forge-app/open-forge-app.tsx

[Pressing the "About" Tab while on the Contact or opportunities page wont scroll to the correct place](https://github.com/openforge/OPENFORGE.IO/issues/100)
- Preload images
- Increase manual page scrolling wait time

Pressing the "About" Tab while on the Contact or opportunities page wont scroll to the correct place

---

firebase.json

Added a rewrites option to firebase.json and ran firebase tools:migrate to fix

fix(firebase): direct urls should not return 404

---

src/pages/app-home/app-home.scss
src/pages/app-home/app-home.tsx

We are reverting back to the previous style of the home page until we can gather more photos for the header.
Labeling this pull request so we have a record of the styling for when and if we inject a photo as a header again.

style(app-home): revert back to previous header with computer screen

---

src/pages/app-home/app-home.scss

This PR fix #150 and center the cards in that size.

fix(): fix issue 150

---

package-lock.json
src/pages/app-contact/app-contact.tsx
src/pages/app-home/app-home.tsx

fixes #190, #191, and #179
Branch is built and pushed to dev server as of 9:40 a.m.

fix(contact, home):  fixes #190, #191, #179

---

src/components/app-footer/app-footer.tsx

fix(app-footer): add linebreak after address

---

src/components/app-nav-header/app-nav-header.scss
src/pages/app-404/app-404.scss
src/pages/app-detailed-service/app-detailed-service.scss
src/pages/app-home/app-home.scss
src/pages/app-home/app-home.tsx

fix #211 and sass linter errors

fix(home): fix issue 211 and sass lint

---

package-lock.json
src/pages/app-detailed-service/app-detailed-service.tsx

Adding working links for try.juntoscope.com and the New Ocean Health Solutions page to the "Check it out" text on the app-developer services page

fix: add working links to "check it out" text

---

src/pages/app-opportunities/app-opportunities.tsx

Updated the value from 60% to 70% on specifically the designer section for opportunities.
Link to Teamwork task:
https://openforge.teamwork.com/#tasks/12012711

fix: update slider values from 60 to 70

---

src/pages/open-forge-app/open-forge-app.tsx

TW task related:
https://openforge.teamwork.com/#tasks/12027980

fix(about): fix redirect issue

---

src/pages/app-team-landing/app-team-landing.tsx

Related Teamwork task:
https://openforge.teamwork.com/#tasks/12028054

fix(about): fix typo on ted page

---

src/components/app-footer/app-footer.scss
src/pages/app-case-study/app-case-study.scss
src/pages/app-detailed-service/app-detailed-service.scss
src/pages/app-opportunities/app-opportunities.scss
src/pages/app-opportunities/app-opportunities.tsx

- fix(opportunities): add underline to links
- refactor(opportunities): renamed duplicate class
- fix(app-footer): add underline to links
- fix(case-study): add underline style to top-link
- fix(detailed-service): update spacing for left and right class
Teamwork Task:
https://openforge.teamwork.com/#tasks/12043851

fix(): add underline to links

---

src/pages/app-home/app-home.scss

Teamwork task:
https://openforge.teamwork.com/#tasks/12051365
Fix home services cards to add extra space for lower screens

fix(home): fix home cards styles

---

src/pages/app-toolbox/app-toolbox.scss
src/pages/app-toolbox/app-toolbox.tsx

Teamwork Task:
https://openforge.teamwork.com/#tasks/12043945

feat(toolbox): add back links

---

src/components.d.ts
src/components/app-nav-header/app-nav-header.tsx
src/pages/app-detailed-service/app-detailed-service.tsx
src/pages/app-opportunities/app-opportunities.tsx
src/pages/app-resources/app-resources.tsx
src/pages/app-team-landing/app-team-landing.tsx
src/pages/open-forge-app/open-forge-app.tsx

Teamwork Task:
https://openforge.teamwork.com/#tasks/12065352

 Fix/navigate non existent

---

src/pages/app-home/app-home.scss

Teamwork Task:
https://openforge.teamwork.com/#tasks/12065304

fix(home): fix our work styles on ipad

---

src/assets/i18n/en.ts

removed double "from" and "one" from page

fix(en.ts): fix two typos on services/app-developer

---

src/components/app-footer/app-footer.scss
src/components/app-footer/app-footer.tsx
src/components/app-nav-header/app-nav-header.tsx

Teamwork task:
https://openforge.teamwork.com/#tasks/12178553

feat(app): make some updates on navbar and footer

---

src/assets/i18n/en.ts
src/components/app-footer/app-footer.tsx

Link to teamwork task for subtask # 2 to update the footer language -
https://openforge.teamwork.com/index.cfm#tasks/12522402

feat(footer): update footer language

---

src/assets/i18n/en.ts
src/components/app-cta/app-cta.scss
src/components/app-cta/app-cta.tsx
src/pages/app-team-landing/app-team-landing.scss
src/pages/app-team-landing/app-team-landing.tsx

In addition to the frontend for the CTA -
- Added localization for the entire app-team-landing view
- Updated a conflicting style in the app-cta style sheet to be inline, instead of overriding all of the .btn styles.

fix(app-team-landing): add separate CTA for app-team-landing

---

src/pages/app-home/app-home.scss

Edited the styling for the header on the home page, made header and first graphic closer together

fix: fix header placement on home page

---

package-lock.json
src/components/app-cta/app-cta.scss
src/pages/app-home/app-home.scss
src/pages/app-home/app-home.tsx

Fixed reference to 'this' for sticky reference

fix(home): fix broken scroll on home page

---

src/pages/app-home/app-home.tsx

fixed bug where carousel wouldn't start on load by forcing bootstrap to reinitialize the component

fix(home): fixed bug where carousel did not start

---

src/assets/fonts/Muli.css
src/assets/fonts/Roboto.css
src/index.html
src/pages/app-home/app-home.tsx
src/pages/open-forge-app/open-forge-app.tsx

perf: add fallback to fonts, add preload to main js, remove double home

---

src/assets/i18n/en.ts
src/components/app-cta/app-cta.scss
src/pages/app-detailed-service/app-detailed-service.scss
src/pages/app-detailed-service/app-detailed-service.tsx

Resolves feedback left on #358

fix(app-deatiled-service): #358 PR revisions

---

src/components.d.ts
src/components/app-blog-card/app-blog-card.scss
src/components/app-blog-card/app-blog-card.tsx
src/components/app-blog-content/app-blog-content.scss
src/components/app-blog-content/app-blog-content.tsx
src/components/app-blog-featured/app-blog-featured.scss
src/components/app-blog-featured/app-blog-featured.tsx
src/pages/app-blog/app-blog.scss
src/pages/app-blog/app-blog.tsx

Task: https://openforge.teamwork.com/#tasks/14052671

Blog newsletter redesign

---

src/pages/app-service-level-agreement/app-service-level-agreement.tsx

fix(sla): removed webp assets from sla page

---

src/components/app-blog-card/app-blog-card.tsx
src/components/app-blog-content/app-blog-content.tsx
src/components/app-blog-featured/app-blog-featured.tsx

Task: https://openforge.teamwork.com/#/tasks/15467722

fix(blog): redirect jedi's author link to twitter

---

src/pages/app-blog/app-blog.tsx

https://openforge.teamwork.com/#tasks/15839033

Added scroll to top between blog pages

---

cypress/integration/app-contact.spec.js
src/assets/i18n/en.ts
src/components/app-footer/app-footer.tsx

Task: https://openforge.teamwork.com/#/tasks/15975224

fix(footer): update social media links

---

package-lock.json
package.json

build(package.json): bump version number to 2.4.0

---

src/index.html

Task: https://openforge.teamwork.com/#/tasks/16322266

feat: add preload property to resources

---

src/components/app-cta/app-cta.scss
src/components/app-cta/app-cta.tsx

Task: https://openforge.teamwork.com/#/tasks/16321466

fix(): cta button hover

---

src/assets/i18n/en.ts
src/pages/app-team-landing/app-team-landing.tsx

https://openforge.teamwork.com/#/tasks/16321542

fix(team-landing): fix the back button to just back

---

src/pages/open-forge-app/open-forge-app.tsx

Task: https://openforge.teamwork.com/#/tasks/16619582

fix: change scrollTopOffset to non falsy value

---

src/components/app-blog-card/app-blog-card.tsx
src/components/app-blog-content/app-blog-content.tsx
src/components/app-blog-featured/app-blog-featured.tsx
src/components/content-graphic/content-graphic.tsx
src/pages/app-contact/app-contact.tsx

Tasks:
https://openforge.teamwork.com/#/tasks/16322274
https://openforge.teamwork.com/#/tasks/16322313

fix: add missing alt property to imgs

---

src/pages/app-blog/app-blog.scss

Task: https://openforge.teamwork.com/#/tasks/16619480

fix: remove incorrect size properties for blog

---

src/assets/i18n/en.ts
src/components/app-nav-header/app-nav-header.scss
src/components/app-nav-header/app-nav-header.tsx
src/pages/open-forge-app/open-forge-app.tsx

https://openforge.teamwork.com/#/tasks/16793557

feat(navbar): update styles to match new design

---

src/pages/open-forge-app/open-forge-app.tsx

Task: https://openforge.teamwork.com/#/tasks/16619463
I didn't like this fix that much but is the only one I could make work. Feel free to suggest other solutions on CR.

fix: check current location to set active class

---

budget.json

Task: https://openforge.teamwork.com/#/tasks/16321672

feat: add budget file

---

src/components/app-footer/app-footer.tsx

https://openforge.teamwork.com/#/tasks/17477484

fix(footer): hide press kit link

---

src/components/app-nav-header/app-nav-header.tsx

https://openforge.teamwork.com/#/tasks/17477847

fix(navbar): hide links

---

src/assets/i18n/en.ts

https://openforge.teamwork.com/#/tasks/17477226

fix(home): project typo

---

src/pages/app-home/app-home.tsx

https://openforge.teamwork.com/#/tasks/17477300

fix(home): hide learn more button

---

src/pages/app-partners/app-partners.scss

https://openforge.teamwork.com/#/tasks/17478459

fix(partners): remove scroll

---

src/index.html

Per our meeting with 215 we were advised to update our google tag scripts to the following. This is a change only within the index.html, and will need to be deployed to test.
Once deployed, we will need follow up with 215 so we can verify the changes.

feature(): replace google tag manager tags per 215 recommendations

---

src/pages/app-our-work-single/app-our-work-single.scss

https://openforge.teamwork.com/#/tasks/17495222

fix(our work): space on right

---

src/pages/app-opportunities/app-opportunities.scss

https://openforge.teamwork.com/#/tasks/17492686

fix(opportunities): update header styles on mobile

---

src/pages/app-partners/app-partners.scss

https://openforge.teamwork.com/#/tasks/17495246

fix(partners): fix carousel scroll

---

src/pages/app-partners/app-partners.scss

https://openforge.teamwork.com/#/tasks/17495247

fix(partners): update styles to center carousel

---

src/components/app-footer/app-footer.tsx

https://openforge.teamwork.com/#/tasks/17493377

fix(footer): hide forge button

---

src/assets/i18n/en.ts
src/pages/app-contact/app-contact.tsx

https://openforge.teamwork.com/#/tasks/17495244

fix(contact): remvoe asterisk from phone

---

src/pages/app-our-work/app-our-work.scss

https://openforge.teamwork.com/#/tasks/17495219

fix(our work): header on tablet

---

src/pages/app-our-work-single/app-our-work-single.scss

https://openforge.teamwork.com/#/tasks/17495229

fix(opportunities): text in two lines mobile

---

src/pages/app-our-work/app-our-work.scss

https://openforge.teamwork.com/#/tasks/17495225

fix(our work): small screens

---

src/pages/app-home/app-home.scss

https://openforge.teamwork.com/#/tasks/17495216

fix(home): remove white space on tablet

---

src/pages/app-partners/app-partners.scss

https://openforge.teamwork.com/#/tasks/17522002

fix(app-partners): center carousel row

---

src/pages/app-blog/app-blog.scss
src/pages/app-blog/app-blog.tsx

https://openforge.teamwork.com/#/tasks/17522185

fix(app-blog): update searchbar for md breakpoint

---

src/pages/app-team-landing/app-team-landing.tsx

https://openforge.teamwork.com/#/tasks/17521988

fix(app-team-landing): add restraint for querySelector for resize

---

src/pages/app-opportunities/app-opportunities.scss

https://openforge.teamwork.com/#/tasks/17522481

fix(app-opportunities): update mobile height of header

---

src/pages/app-partners/app-partners.scss

https://openforge.teamwork.com/#/tasks/17522007

fix(app-partners): update cta spacing for all sizes

---

src/pages/app-partners/app-partners.scss
src/pages/app-partners/app-partners.tsx

https://openforge.teamwork.com/#/tasks/17522002
^ fix found during another round of regression with the animation causing height issues on slide.

fix(app-partners): update carousel positioning and height

---

src/pages/app-team-landing/app-team-landing.scss
src/pages/app-team-landing/app-team-landing.tsx

https://openforge.teamwork.com/#/tasks/17521988
Migrated all the resize functionality to a function that is called by the window.addEventListener resize. Then created a window.removeEventListener for the resize to prevent this from being called or used outside of this page, or any data carrying over.

fix(app-team-landing): migrate resize to function and add remove event listener

---

src/components/app-footer/app-footer.tsx

https://openforge.teamwork.com/#/tasks/17524772

fix(footer): add accessibility links aria label

---

src/components/app-blog-featured-home/app-blog-featured-home.tsx

https://openforge.teamwork.com/#/tasks/17524780

fix(): accessibility ids

---

src/index.html

https://openforge.teamwork.com/#/projects/235303/tasks/17524769

fix(): update bootstrap and jquery to avoid vulnerabilities

---

src/components/app-blog-card/app-blog-card.scss
src/components/app-blog-card/app-blog-card.tsx
src/components/app-blog-content/app-blog-content.scss
src/components/app-blog-content/app-blog-content.tsx
src/components/app-blog-featured-home/app-blog-featured-home.scss
src/components/app-blog-featured-home/app-blog-featured-home.tsx
src/components/app-blog-featured/app-blog-featured.scss
src/components/app-blog-featured/app-blog-featured.tsx
src/pages/app-blog-post/app-blog-post.tsx
src/pages/app-home/app-home.scss
src/pages/app-home/app-home.tsx
src/pages/app-our-work-single/app-our-work-single.scss
src/pages/app-our-work-single/app-our-work-single.tsx
src/pages/app-our-work/app-our-work.scss
src/pages/app-our-work/app-our-work.tsx
src/pages/app-partners/app-partners.tsx

https://openforge.teamwork.com/#/tasks/17524808

fix(): perf images

---

src/pages/app-our-work-single/app-our-work-single.scss
src/pages/app-our-work/app-our-work.scss

https://openforge.teamwork.com/#/tasks/17524758

fix(our work): our work store buttons

---

src/components/app-nav-header/app-nav-header.tsx
src/pages/app-our-work-single/app-our-work-single.tsx
src/pages/app-our-work/app-our-work.tsx
src/pages/open-forge-app/open-forge-app.tsx

https://openforge.teamwork.com/#/tasks/17524757

fix(navbar): our work active state

---

src/components/app-blog-featured-home/app-blog-featured-home.tsx

Fixes the details of the second featured post in the home page.
https://openforge.teamwork.com/#/tasks/17751378

fix(): incorrect second post details

---

src/components/app-cta/app-cta.scss
src/pages/app-home/app-home.scss

https://openforge.teamwork.com/#/tasks/17524788

fix(): accessibility contrast ratio

---

firebase.json

https://openforge.teamwork.com/#/tasks/17524811
I updated the Cache TTL for the files that are under our control, only left 4 from initial 23 that are not under our control so we might need check them with the dev team to see how we can update that Cache TTL 
I added Cache for 1 year for assets/images since those are not going to change (if change is the entire image to another one) so thats fine.
And for js files I added like 3 months cache since the files contain hash code and the filename changes.

fix(): update cahte ttl

---

src/pages/app-opportunities/app-opportunities.tsx

https://openforge.teamwork.com/index.cfm#/projects/235303/tasks/17524761

fix(opportunities): adjust the scroll into form

---

cypress/integration/app-footer.spec.js
package-lock.json
package.json
src/components/app-footer/app-footer.tsx

chore(package.json): bump verson to 2.5.2

---

src/components/content-graphic/content-graphic.scss

https://openforge.teamwork.com/#/tasks/17495271
I checked the styles and there was not any style related to bold, so I just updated the list items to have the same styles than the other texts so it feels like there is no bold.

fix(oportunities): fix styles
